details:
  namespace: student124-bookinfo-prd
  image: ghcr.io/crisspina/bookinfo-details
  tag: prd
  replicas: 1
  imagePullSecrets: registry-bookinfo
  port: 9080
  healthCheckPath: "/health"
ingress:  
  host: bookinfo.opsta.net
  path: "/student124/details(/|$)(.*)"
  serviceType: ClusterIP
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
extraEnv:
  COMMIT_SHA: CHANGEME


